name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_job:
    runs-on: windows-latest
    name: Build Job
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: true
      - name: Install DocFX
        run: dotnet tool update -g docfx
        env:
          CI: true
      - name: Restore NuGet
        run: dotnet restore "src/NuGetPackages"
      - name: Build
        run: dotnet build "src/NuGetPackages" --configuration Release
      - name: Build Documentation
        id: build-documentation
        run: |
          docfx metadata
          docfx build --warningsAsErrors
        shell: powershell
      - name: Zip artifact for deployment
        run: Compress-Archive -Path _site/* -DestinationPath .\_site.zip
      - name: Publish results
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: release
          path: _site.zip
  
  deploy_job_Storage_Account:
    if: (github.event_name == 'push' && github.repository == 'SkylineCommunications/dataminer-docs')
    runs-on: ubuntu-latest
    needs: build_job
    name: Deploy Job to Storage account
    steps:
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806
        with:
          name: release
          path: .
      - name: Unzip artifact for deployment
        run: Expand-Archive -Path _site.zip -DestinationPath ./_site
        shell: pwsh
      - name: Delete files that should not be indexed by Azure Search Service
        run: |
          rm -f ./_site/404.html
          rm -f ./_site/README.html
          find ./_site -name 'toc.html' -type f -delete
      - name: Upload the new files
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_ACCOUNT_DOCS_CONNECTION_STRING }}
        run: |
          wget https://aka.ms/downloadazcopy-v10-linux
          tar -xvf downloadazcopy-v10-linux
          sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/
          azcopy --version
          az storage blob sync \
            --source _site \
            --container docs
  
  deploy_job_SA_SWA:
    if: (github.event_name == 'push' && github.repository == 'SkylineCommunications/dataminer-docs')
    runs-on: ubuntu-latest
    needs: build_job
    name: Deploy Job to SA with SWA and FD
    steps:
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806
        with:
          name: release
          path: .
      - name: Unzip artifact for deployment
        run: Expand-Archive -Path _site.zip -DestinationPath ./_site
        shell: pwsh
      - name: Upload the new files
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_SA_DOCS_SWA }}
        run: |
          wget https://aka.ms/downloadazcopy-v10-linux
          tar -xvf downloadazcopy-v10-linux
          sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/
          azcopy --version
          az storage blob sync \
            --source _site \
            --container '$web'
          
  reindex_azure_search:
    runs-on: ubuntu-latest
    needs: deploy_job_Storage_Account
    name: Re-index azure search
    steps:
    - name: Azure Cognitive Search Reindex
      # version 2.0.3
      uses: andrewconnell/azure-search-index@bda856c34c857a2729826cd3f0c70fc3d7cf273a
      with:
        # Name of the Azure Cognitive Search resource.
        azure-search-instance: docs-srch
        # Search indexer to reindex
        azure-search-indexer: azureblob-indexer2
        # Admin key used to connect to Azure Cognitive Search instance
        azure-search-admin-key: ${{ secrets.AZURE_SEARCH_KEY }}
